// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erpzpfbmaptluyuqxwqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycHpwZmJtYXB0bHV5dXF4d3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODc5NzEsImV4cCI6MjA2NDY2Mzk3MX0.JWVxDGktdS4EYzg9Ci9HbuYBBGvA9xeNgizqlbGv3dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);